spring:
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7643970cb5bdb570ac7c688d2c6ea85e
            client-secret: ""
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 600000       # 10분 (ms)
  refresh-token-expiration: 86400000    # 1일 (ms)
  header: Authorization

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter: DEBUG

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
      include-message: always
      include-binding-errors: always
  forward-headers-strategy: framework
  
aws:
  s3:
    presigned:
      expire-minutes: 15
    bucket: ceos-promesa

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics  # 노출할 엔드포인트 목록
        exclude: beans, env              # 제외할 엔드포인트 목록
