spring:
  config:
    activate:
      on-profile: prod

  datasource:
    # RDS 엔드포인트(호스트+포트), DB 이름을 환경변수 RDS_URL로 전달
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      url: redis://${REDIS_HOST}:${REDIS_PORT:6379}

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://promesa.co.kr/api/login/oauth2/code/kakao

logging:
  level:
    # 운영에서는 SQL 로그는 꺼 둠
    org.hibernate.SQL: WARN

management:
  metrics:
    binders:
      system:
        enabled: false      # ProcessorMetrics, DiskSpaceMetrics 등 OS 레벨 메트릭 전체
      processor:
        enabled: false      # CPU 바인더 (별도)
      tomcat:
        enabled: false      # TomcatMetrics 빈 비활성화
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
