spring:
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7643970cb5bdb570ac7c688d2c6ea85e
            client-secret: ""
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter: DEBUG

server:
  port: 8081

aws:
  s3:
    presigned:
      expire-minutes: 15
    bucket: ceos-promesa